name: CI
on: [push]
jobs:
  autoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            sudo snap install zig --classic --edge
            zig version
      - name: build
        run: zig build
      - name: test
        run: zig test src/autoring.zig
